//
//  GBuffer.metal
//  ToyFlightSimulator
//
//  Created by Albertino Padin on 1/27/23.
//

#include <metal_stdlib>
using namespace metal;

#import "ShaderDefinitions.h"
#import "ShaderHelpers.h"
#import "Lighting.metal"

// Per-vertex inputs fed by vertex buffer laid out with MTLVertexDescriptor in Metal API
typedef struct {
    float3 position  [[ attribute(TFSVertexAttributePosition) ]];
    float2 tex_coord [[ attribute(TFSVertexAttributeTexcoord) ]];
    half3  normal    [[ attribute(TFSVertexAttributeNormal) ]];
    half3  tangent   [[ attribute(TFSVertexAttributeTangent) ]];
    half3  bitangent [[ attribute(TFSVertexAttributeBitangent) ]];
} DescriptorDefinedVertex;

// Vertex shader outputs and per-fragment inputs.  Includes clip-space position and vertex outputs
// interpolated by rasterizer and fed to each fragment generated by clip-space primitives.
typedef struct {
    float4 position [[ position ]];
    float4 color;
    float4 objectColor;
    float2 tex_coord;
    float3 worldPosition;   // perspective-correct; fragment derives viewSpaceDepth + cascade shadow pos
    float3 worldNormal;     // for slope-scaled shadow bias
    float3 eye_position;
    half3 tangent;
    half3 bitangent;
    half3 normal;
    uint instanceId;
    bool useObjectColor;
} ColorInOut;

vertex ColorInOut gbuffer_vertex(VertexIn                   in              [[ stage_in ]],
                                 constant SceneConstants    &sceneConstants [[ buffer(TFSBufferIndexSceneConstants) ]],
                                 constant ModelConstants    *modelConstants [[ buffer(TFSBufferModelConstants) ]],
                                 uint                       instanceId      [[ instance_id ]]) {
    ModelConstants modelInstance = modelConstants[instanceId];
    float4 modelPosition = float4(in.position, 1.0);
    float4 worldPosition = modelInstance.modelMatrix * modelPosition;
    float4 eyePosition = sceneConstants.viewMatrix * worldPosition;

    ColorInOut out = {
        .color = in.color,
        .objectColor = modelInstance.objectColor,
        .tex_coord = in.textureCoordinate,
        .position = sceneConstants.projectionMatrix * eyePosition,
        .worldPosition = worldPosition.xyz / worldPosition.w,
        .worldNormal = modelInstance.normalMatrix * in.normal,
        .eye_position = eyePosition.xyz,
        .tangent = half3(normalize(modelInstance.normalMatrix * in.tangent)),
        .bitangent = half3(-normalize(modelInstance.normalMatrix * in.bitangent)),
        .normal = half3(normalize(modelInstance.normalMatrix * in.normal)),
        .instanceId = instanceId,
        .useObjectColor = modelInstance.useObjectColor
    };

    return out;
}

vertex ColorInOut gbuffer_animated_vertex(VertexIn                   in              [[ stage_in ]],
                                          constant SceneConstants    &sceneConstants [[ buffer(TFSBufferIndexSceneConstants) ]],
                                          constant ModelConstants    *modelConstants [[ buffer(TFSBufferModelConstants) ]],
                                          constant float4x4          *jointMatrices  [[ buffer(TFSBufferIndexJointBuffer) ]],
                                          uint                       instanceId      [[ instance_id ]]) {
    ModelConstants modelInstance = modelConstants[instanceId];
    float4 modelPosition = float4(in.position, 1.0);
    float4 normal = float4(in.normal, 0);
    
    float4x4 skinMatrix = BlendJointMatrix(jointMatrices, in.joints, in.jointWeights);
    modelPosition = skinMatrix * modelPosition;
    normal = skinMatrix * normal;
    float3 skinnedTangent = (skinMatrix * float4(in.tangent, 0)).xyz;
    float3 skinnedBitangent = (skinMatrix * float4(in.bitangent, 0)).xyz;

    float4 worldPosition = modelInstance.modelMatrix * modelPosition;
    float4 eyePosition = sceneConstants.viewMatrix * worldPosition;

    ColorInOut out = {
        .color = in.color,
        .objectColor = modelInstance.objectColor,
        .tex_coord = in.textureCoordinate,
        .position = sceneConstants.projectionMatrix * eyePosition,
        .worldPosition = worldPosition.xyz / worldPosition.w,
        .worldNormal = modelInstance.normalMatrix * normal.xyz,
        .eye_position = eyePosition.xyz,
        .tangent = half3(normalize(modelInstance.normalMatrix * skinnedTangent)),
        .bitangent = half3(-normalize(modelInstance.normalMatrix * skinnedBitangent)),
        .normal = half3(normalize(modelInstance.normalMatrix * normal.xyz)),
        .instanceId = instanceId,
        .useObjectColor = modelInstance.useObjectColor
    };

    return out;
}

fragment GBufferData gbuffer_fragment_base(ColorInOut           in             [[ stage_in ]],
                                           constant SceneConstants &sceneConstants [[ buffer(TFSBufferIndexSceneConstants) ]],
                                           constant LightData      &lightData      [[ buffer(TFSBufferDirectionalLightData) ]],
                                           depth2d_array<float> shadowArray    [[ texture(TFSTextureIndexShadow) ]])
{
    half4 base_color = half4(in.color);
    half specularContribution = 1.0;  // Hardcoded for base
    
    // No normal map is bound in the base pass: in.normal is the interpolated
    // eye-space geometric normal, already in [-1,1]. ApplyNormalMapEye's
    // [0,1] -> [-1,1] decode is for texture samples only; just renormalize
    // (interpolation denormalizes).
    half3 eye_normal = normalize(in.normal);

    // Cascade-aware shadow. eye_position.z is true view-space depth, the metric
    // cascadeSplitDepths is defined in — a radial camera distance would promote
    // screen-edge fragments into coarser cascades early.
    float shadow_sample = Lighting::CalculateShadow(in.worldPosition,
                                                    in.eye_position.z,
                                                    in.worldNormal,
                                                    lightData,
                                                    shadowArray);

    // Store shadow with albedo in unused fourth channel;
    // Store the specular contribution with the normal in unused fourth channel.

    // Fill in on-chip geometry buffer data
    GBufferData gBuffer = {
        .albedo_specular = half4(base_color.xyz, specularContribution),
        .normal_shadow = half4(eye_normal.xyz, shadow_sample),
        .depth = in.eye_position.z
    };

    return gBuffer;
}

fragment GBufferData gbuffer_fragment_material(
                    ColorInOut                          in             [[ stage_in ]],
                    constant SceneConstants            &sceneConstants [[ buffer(TFSBufferIndexSceneConstants) ]],
                    constant LightData                 &lightData      [[ buffer(TFSBufferDirectionalLightData) ]],
                    constant MaterialProperties        &material       [[ buffer(TFSBufferIndexMaterial) ]],
                    constant MaterialTextureTransforms &uvXforms       [[ buffer(TFSBufferIndexMaterialTextureTransforms) ]],
                    sampler                             sampler2d      [[ sampler(0) ]],
                    texture2d<half>                     baseColorMap   [[ texture(TFSTextureIndexBaseColor) ]],
                    texture2d<half>                     normalMap      [[ texture(TFSTextureIndexNormal) ]],
                    texture2d<half>                     specularMap    [[ texture(TFSTextureIndexSpecular) ]],
                    depth2d_array<float>                shadowArray    [[ texture(TFSTextureIndexShadow) ]])
{
    float2 baseUV     = in.tex_coord.xy;
    float2 normalUV   = in.tex_coord.xy;
    float2 specularUV = in.tex_coord.xy;
    if (uvXforms.hasTextureTransforms) {
        baseUV     = ApplyUVTransform(in.tex_coord.xy, uvXforms.baseColorUVTransform);
        normalUV   = ApplyUVTransform(in.tex_coord.xy, uvXforms.normalUVTransform);
        specularUV = ApplyUVTransform(in.tex_coord.xy, uvXforms.specularUVTransform);
    }

    half4 base_color_sample = half4(ResolveBaseColor(in.useObjectColor,
                                                     in.objectColor,
                                                     in.color,
                                                     baseColorMap,
                                                     sampler2d,
                                                     baseUV));
    
    half3 eye_normal;
    // The guard is load-bearing: submeshes without a normal map bind nothing at
    // this index (sampling a null texture is undefined), and a geometric normal
    // is already in [-1,1] so it must skip the [0,1] sample decode.
    if (!in.useObjectColor && !is_null_texture(normalMap)) {
        eye_normal = ApplyNormalMapEye(normalMap.sample(sampler2d, normalUV).xyz,
                                       in.tangent,
                                       in.bitangent,
                                       in.normal);
    } else {
        eye_normal = normalize(in.normal);
    }
    
    half specular_contrib;

    if (!in.useObjectColor && !is_null_texture(specularMap)) {
        specular_contrib = specularMap.sample(sampler2d, specularUV).r;
    } else {
        specular_contrib = 1.0;
    }
    
    // Cascade-aware shadow. eye_position.z is true view-space depth, the metric
    // cascadeSplitDepths is defined in — a radial camera distance would promote
    // screen-edge fragments into coarser cascades early.
    float shadow_sample = Lighting::CalculateShadow(in.worldPosition,
                                                    in.eye_position.z,
                                                    in.worldNormal,
                                                    lightData,
                                                    shadowArray);

    // Store shadow with albedo in unused fourth channel;
    // Store the specular contribution with the normal in unused fourth channel.

    // Fill in on-chip geometry buffer data
    GBufferData gBuffer = {
        .albedo_specular = half4(base_color_sample.xyz, specular_contrib),
        .normal_shadow = half4(eye_normal.xyz, shadow_sample),
        .depth = in.eye_position.z
    };

    return gBuffer;
}
